### ISSUE TITLE
TypeError: Cannot read property 'formatted_address' of undefined

### ISSUE THREAD

**Issue by tkothe** [jsolis/hubot-forecastio#4]
I am getting the following error running the bot on heroku

```

2015-11-26T17:42:04.286042+00:00 app[web.1]: [Thu Nov 26 2015 17:42:04 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'formatted_address' of undefined
2015-11-26T17:42:04.286046+00:00 app[web.1]:   at /app/node_modules/hubot-forecastio/src/forecastio.coffee:25:7, <js>:18:55
2015-11-26T17:42:04.286048+00:00 app[web.1]:   at IncomingMessage.<anonymous> (/app/node_modules/hubot/node_modules/scoped-http-client/src/index.js:95:22)
2015-11-26T17:42:04.286049+00:00 app[web.1]:   at IncomingMessage.emit (events.js:117:20)
2015-11-26T17:42:04.286050+00:00 app[web.1]:   at _stream_readable.js:944:16
2015-11-26T17:42:04.286051+00:00 app[web.1]:   at process._tickCallback (node.js:448:13)
```

I am running e.g. "weather in cancun" and accessing 
http://maps.googleapis.com/maps/api/geocode/json?address=cancun&sensor=false

actually works fine. Any idea what could be wrong?

**Comment by jsolis** [comment]
That does seem strange.  What version of `hubot-forecastion` are you running? I had accepted a pull request a few versions ago which changed from a `hear` to a `respond` but your example doesn't mention a robot name. Not sure if you just omitted it or you're running an older version.

I just tried "cancun" in my bot and got a valid response:

```
In Cancún, Quintana Roo, Mexico, it is currently 81.55. Feels like 85.24.  Partly cloudy until this afternoon.
```

**Comment by tkothe** [comment]
Hi @jsolis, 
it turns out I have some pretty random behavior. I also got a valid response for the query some time later (same information as you got) but then it failed again. 
I got the suspicion that my issue is that I also run [hubot-forecast](https://github.com/jeffbyrnes/hubot-forecast) at the same time. I somehow feel that hubot-forecast and hubot-forecastio somehow mess things up between the two. (for whatever reason, hubot-forecast now shows US units even thought it was working fine with SI units two days ago).
Do you have any information on conflicts between the two?
I will try running both separately and let you know. For now everything is working fine so we can close this issue. Sorry for the mess ;)

**Comment by jsolis** [comment]
I'm not aware of any but now I'm interested. Let me know if you figure it out. No worries!
